#!/usr/bin/env python3
"""Write _generated/repos.md: a "More on GitHub" list for the Software page.

Lists your public repositories, newest activity first, skipping:
  * forks and archived repos,
  * this site's repo and your profile repo,
  * anything named in data/featured_repos.txt (those are described by hand in software.qmd).

Standard library only. Runs in the publish workflow before each build.
If GitHub cannot be reached it leaves the existing file alone and exits 0,
so a network hiccup never breaks the site build.

    python scripts/fetch_repos.py                 # uses the owner from GITHUB_REPOSITORY_OWNER, else "nexusofthings"
    python scripts/fetch_repos.py --user someone
"""
import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "_generated" / "repos.md"
FEATURED = ROOT / "data" / "featured_repos.txt"
EMPTY = "<!-- Generated by scripts/fetch_repos.py. No other public repositories to list. -->\n"


def read_featured() -> set:
    if not FEATURED.exists():
        return set()
    names = set()
    for line in FEATURED.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            names.add(line.lower())
    return names


def fetch(user: str) -> list:
    repos, page = [], 1
    while True:
        url = f"https://api.github.com/users/{user}/repos?type=owner&sort=pushed&per_page=100&page={page}"
        req = urllib.request.Request(url, headers={"Accept": "application/vnd.github+json", "User-Agent": "site-builder"})
        token = os.environ.get("GITHUB_TOKEN")
        if token:
            req.add_header("Authorization", f"Bearer {token}")
        with urllib.request.urlopen(req, timeout=20) as resp:
            batch = json.load(resp)
        repos.extend(batch)
        if len(batch) < 100:
            return repos
        page += 1


def esc(text: str) -> str:
    """Escape characters that markdown would otherwise interpret."""
    return re.sub(r"([\\`*_\[\]<>])", r"\\\1", text or "")


def render(repos: list) -> str:
    if not repos:
        return EMPTY
    out = ["---", "", "## More on GitHub", ""]
    for r in repos:
        meta = [m for m in (r.get("language"),
                            f"{r['stargazers_count']} stars" if r.get("stargazers_count") else None,
                            "updated " + r["pushed_at"][:7] if r.get("pushed_at") else None) if m]
        head = f"- **[{r['name']}]({r['html_url']})**"
        if r.get("description"):
            head += f": {esc(r['description'])}"
        if meta:
            head += "\\\n  [" + " \u00b7 ".join(meta) + "]{.repo-meta}"
        out.append(head)
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--user", default=os.environ.get("GITHUB_REPOSITORY_OWNER", "nexusofthings"))
    args = parser.parse_args()

    try:
        repos = fetch(args.user)
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as err:
        print(f"::warning::Could not refresh the GitHub repo list ({err}). Keeping the existing file.")
        return 0

    skip = read_featured() | {args.user.lower(), f"{args.user.lower()}.github.io"}
    keep = [r for r in repos
            if not r.get("fork") and not r.get("archived") and not r.get("private")
            and r["name"].lower() not in skip]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    text = render(keep)
    if OUT.exists() and OUT.read_text(encoding="utf-8") == text:
        print(f"{len(keep)} repositories listed (no change).")
    else:
        OUT.write_text(text, encoding="utf-8")
        print(f"{len(keep)} repositories listed (updated {OUT.name}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
